name: Daily Release

on:
  schedule:
    - cron:  '0 14 * * *'

jobs:
  daily_release:
    name: Daily Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Portable Python Environments - env_python.sh
        run: |
          ./run.sh env_python.sh
      - name: Build Portable Python Environments - env_pyspark.sh
        run: |
          ./run.sh env_pyspark.sh
      - name: Build Portable Python Environments - env_pyspark_tf.sh
        run: |
          ./run.sh env_pyspark_tf.sh
      - name: Build Portable Python Environments - env_pyspark_torch.sh
        run: |
          ./run.sh env_pyspark_torch.sh
      - name: Set Environment Variable
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: daily_build_${{ TODAY }}
          files: |
            *.tar.gz
