name: Daily Pre-release

on:
  schedule:
    - cron:  '0 14 * * *'

jobs:
  daily_pre_release:
    name: Daily Pre-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Portable Python Environments - env_python.sh
        run: |
          ./run.sh env_python.sh
      - name: Build Portable Python Environments - env_pyspark.sh
        run: |
          ./run.sh env_pyspark.sh
      - name: Build Portable Python Environments - env_pyspark_tf.sh
        run: |
          ./run.sh env_pyspark_tf.sh
      - name: Build Portable Python Environments - env_pyspark_torch.sh
        run: |
          ./run.sh env_pyspark_torch.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          automatic_release_tag: daily_release 
          files: |
            *.tar.gz
